spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  cloud:
    function:
      definition: testProducer
    stream:
      bindings:
        testProducer-out-0:
          destination: demo_country
      kafka:
        binder:
          brokers: ${kafka_brokers:localhost}
          auto-create-topics: ${kafka_topics_auto_create:false}

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8090
